version: '4.24'

services:
  web:
    # Берем Dockerfile из каталога app
    build: ./backend
    # Запускаем тестовый сервер
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    # Открываем порт 8000 внутри и снаружи
    ports:
      - 8000:8000
    # Файл содержащий переменные для контейнера
    env_file:
      - ./.env.prod
    # Дожидаемся запуска контейнера db
    depends_on:
      - db
  db:
      image: postgres:15
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=super_user
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=default_store_db

volumes:
  postgres_data: