# Generated by Django 4.2.8 on 2024-01-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default title', max_length=128, verbose_name='Заголовок на странице')),
                ('content', models.TextField(default="Default shop empty content 'about page'!", verbose_name="Контент на странице 'О нас'")),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время описания')),
            ],
            options={
                'verbose_name': "Контент на странице 'О нас'",
                'verbose_name_plural': "Контент на странице 'О нас'",
                'db_table': 'about_page_content',
            },
        ),
        migrations.CreateModel(
            name='IndexPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default title', max_length=128, verbose_name='Заголовок на странице')),
                ('content', models.TextField(default='Default shop empty content!', verbose_name='Контент на главной странице')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время описания')),
            ],
            options={
                'verbose_name': 'Контент на главной странице',
                'verbose_name_plural': 'Контент на главной странице',
                'db_table': 'index_page_content',
            },
        ),
        migrations.CreateModel(
            name='InformationPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default title', max_length=128, verbose_name='Заголовок на странице')),
                ('content', models.TextField(default="Default shop empty content 'information'!", verbose_name="Контент на странице 'Контактная информация'")),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время описания')),
            ],
            options={
                'verbose_name': "Контент на странице 'Контактная информация'",
                'verbose_name_plural': "Контент на странице 'Контактная информация'",
                'db_table': 'information_page_content',
            },
        ),
        migrations.CreateModel(
            name='PayAndDeliveryPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default title', max_length=128, verbose_name='Заголовок на странице')),
                ('content', models.TextField(default="Default shop empty content 'pay and delivery'!", verbose_name="Контент на странице 'Оплата и доставка'")),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время описания')),
            ],
            options={
                'verbose_name': "Контент на странице 'Оплата и доставка'",
                'verbose_name_plural': "Контент на странице 'Оплата и доставка'",
                'db_table': 'pay_and_delivery_page_content',
            },
        ),
    ]
