# Generated by Django 4.2.8 on 2024-01-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagecontent',
            name='text_in_page',
            field=models.TextField(default='Text on about page', verbose_name='Текст на странице'),
        ),
        migrations.AddField(
            model_name='informationpagecontent',
            name='text_in_page',
            field=models.TextField(default="Text on 'pay and delivery' page", verbose_name='Текст на странице'),
        ),
        migrations.AddField(
            model_name='payanddeliverypagecontent',
            name='text_in_page',
            field=models.TextField(default="Text on 'pay and delivery' page", verbose_name='Текст на странице'),
        ),
    ]
